server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/phonebook_db}
spring.datasource.username=${DATABASE_USERNAME:phonebook_user}
spring.datasource.password=${DATABASE_PASSWORD:phonebook_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false